name: Update dependencies

on:
  workflow_dispatch: {}

jobs:
  update-dependencies:
    name: Updating dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - run: nix develop -c git-create-pr
