name: Update dependencies

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 9 * * *'
jobs:
  update-dependencies:
    name: Updating dependencies
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - uses: cachix/install-nix-action@v19
      - run: nix develop -c git-create-pr
