name: Linting

on:
  push:
    branches-ignore:
      - 'main'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
      - run: nix flake check
