name: Linting

on:
  push:
    branches:
      - '!main'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - run: nix flake check
