name: Create a new release

on:
  workflow_dispatch: {}

jobs:
  new-release:
    name: Creating a new release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - uses: cachix/install-nix-action@V28
      - run: nix develop .#new-release -c new-release
